### ISSUE TITLE
Connection Exception

### ISSUE THREAD

**Issue by Xx-YUU-xX** [mdbell/Noexes#11]
me.mdbell.noexs.core.ConnectionException: Result{mod=349, desc=9}
	at me.mdbell.noexs.core.Debugger.readInfo(Debugger.java:525)
	at me.mdbell.noexs.core.Debugger.query(Debugger.java:375)
	at me.mdbell.noexs.dump.DumpRegionSupplier$2.init(DumpRegionSupplier.java:82)
	at me.mdbell.noexs.dump.DumpRegionSupplier$2.getSize(DumpRegionSupplier.java:73)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.createDump(MemorySearchService.java:337)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.fullSearch(MemorySearchService.java:247)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:192)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:175)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by mdbell** [comment]
https://github.com/mdbell/Noexes/blob/master/server/source/noexs/include/errors.h#L17
