### ISSUE TITLE
me.mdbell.noexs.core.ConnectionException

### ISSUE THREAD

**Issue by soliveau** [mdbell/Noexes#17]
me.mdbell.noexs.core.ConnectionException: Result{mod=1, desc=106}
	at me.mdbell.noexs.core.Debugger.readmem(Debugger.java:274)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.createDump(MemorySearchService.java:374)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.refineSearch(MemorySearchService.java:214)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:190)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:175)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by soliveau** [comment]
i wanted to double check EVERYTHING before leaving this, it happens to me on the latest 1.1.2 and 1.1.1.

**Comment by mdbell** [comment]
So you provided no context with what you were doing, but going by the provided error code (mod 1, desc 106, and using https://switchbrew.org/wiki/Error_codes#Error_codes to get it's meaning), you were refining a search and it gave you this exception... My best guess is that between the inital search and when you refined the game deallocated some memory (most likely by loading a new area), namely some memory we were trying to check.

If that is the case then this is a bug I need to fix. Can you confirm?

**Comment by soliveau** [comment]
yeah, sorry. i did in my initial post but not upon re-editing it...  i should not post late at night.

it happens on the second search, every time. if i try another search after the second, it tries to dump about 400gigs. the game i was searching was south park: the fractured but whole.

**Comment by ALETTERR** [comment]
Can I ask if this problem can be solved

**Comment by wobblemaster** [comment]
Was this ever solved in the end? I'm getting the exact same problem so can't really do anything with the program. My error message is: 

```
me.mdbell.noexs.core.ConnectionException: Result{mod=1, desc=106}
        at me.mdbell.noexs.core.Debugger.readmem(Debugger.java:274)
        at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.createDump(MemorySearchService.java:373)
        at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.refineSearch(MemorySearchService.java:211)
        at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:187)
        at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:172)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)


```
