### ISSUE TITLE
me.mdbell.noexs.core.ConnectionException: Result{mod=1, desc=114}

### ISSUE THREAD

**Issue by rushairer** [mdbell/Noexes#20]
When I press the 'Search' button, It alert that
```
me.mdbell.noexs.core.ConnectionException: Result{mod=1, desc=114}
        at me.mdbell.noexs.core.Debugger.readInfo(Debugger.java:525)
        at me.mdbell.noexs.core.Debugger.query(Debugger.java:375)
        at me.mdbell.noexs.dump.DumpRegionSupplier$2.init(DumpRegionSupplier.java:82)
        at me.mdbell.noexs.dump.DumpRegionSupplier$2.getSize(DumpRegionSupplier.java:73)
        at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.createDump(MemorySearchService.java:337)
        at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.fullSearch(MemorySearchService.java:247)
        at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:192)
        at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:175)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

,then I press 'Restart Search', 'Search', It will be processing a long time,but the dump file size is still 0

**Comment by rushairer** [comment]
Sorry, I did not attach it
