### ISSUE TITLE
Crash on Dumping Ram

### ISSUE THREAD

**Issue by Bappsack** [mdbell/Noexes#36]
On Large Games (ex. SwSh) it results almost anytime in a Connection Exception crash when u search & compare the current dump for a value, also sometimes on the first dump aswell.

Related function: https://github.com/mdbell/Noexes/blob/8e8a75daec47a6889d2f90ee025b70d0515c35c5/client/src/me/mdbell/noexs/core/Debugger.java#L259-L285

Triggered Exception:
https://github.com/mdbell/Noexes/blob/8e8a75daec47a6889d2f90ee025b70d0515c35c5/client/src/me/mdbell/noexs/core/Debugger.java#L272-L275

**Comment by mdbell** [comment]
Could you provide the generated stack trace? It should contain an error code that would help with debugging your issue.

**Comment by Bappsack** [comment]
ConnectionException

Result[mod=1, desc=106}

The exception stacktrace was:
> me.mdbell.noexs.core.ConnectionException: Result{mod=1, desc=106}
	at me.mdbell.noexs.core.Debugger.readmem(Debugger.java:274)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.createDump(MemorySearchService.java:373)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.refineSearch(MemorySearchService.java:211)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:187)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:172)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.concurrent.Service.lambda$executeTask$6(Service.java:725)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by mdbell** [comment]
The game is deallocating memory between dumps, there is already an issue for it (#17 to be exact). I'm going to close this issue as it it a duplicate.
