### ISSUE TITLE
not enough free space for dump!

### ISSUE THREAD

**Issue by mcpolo99** [mdbell/Noexes#47]
I do have alot of space on pc and also alot of space on sdcard, where is the  problem?

not enough free space for dump!

java.io.IOException: Not enough free space for dump!
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.createDump(MemorySearchService.java:338)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.fullSearch(MemorySearchService.java:247)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:192)
	at me.mdbell.noexs.ui.services.MemorySearchService$SearchTask.call(MemorySearchService.java:175)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by mdbell** [comment]
Noexes tries to create a folder in the same directly as the .jar file called "tmp", and then before dumping any data it tries to estimate if you have enough free space for the dump. Check to make sure you have write permissions in the same directory as noexes. Only other thing I could think of is that the game maps a ton of extra stuff into memory, if that's the case try to only check specific regions (like the heap)

**Comment by masagrator** [comment]
> Noexes tries to create a folder in the same directly as the .jar file

Iirc on Windows it was not creating where jar is (real directory), but where is current working directory (in cmd it's %~dp0). That's why when I wanted to have .cmd running jnoexs from different folder, first I needed to change directory instead of directly calling jar.
